# Generated by Django 4.1 on 2022-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_content_image_alter_author_author_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(default='no_image.jpg', upload_to='images/2022/09/05', verbose_name='Изображение'),
        ),
    ]
