# Generated by Django 4.1 on 2022-09-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Имя категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(default='no_image.jpg', upload_to='images', verbose_name='Изображение'),
        ),
    ]
