# Generated by Django 4.1 on 2022-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_author_language_author_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='author',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32, verbose_name='Часовой пояс'),
        ),
    ]
