openapi: 3.0.2
info:
  title: 'News Paper'
  version: '0.3'
paths:
  /api/v1/post/:
    get:
      operationId: listPosts
      description: 'Articles'
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: id
        required: false
        in: query
        description: id
        schema:
          type: string
      - name: name_ru
        required: false
        in: query
        description: name_ru
        schema:
          type: string
      - name: name_en
        required: false
        in: query
        description: name_en
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - api
    post:
      operationId: createPost
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - api
  /api/v1/post/{id}/:
    get:
      operationId: retrievePost
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u0441\u0442\
          ."
        schema:
          type: string
      - name: id
        required: false
        in: query
        description: id
        schema:
          type: string
      - name: name_ru
        required: false
        in: query
        description: name_ru
        schema:
          type: string
      - name: name_en
        required: false
        in: query
        description: name_en
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - api
    put:
      operationId: updatePost
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u0441\u0442\
          ."
        schema:
          type: string
      - name: id
        required: false
        in: query
        description: id
        schema:
          type: string
      - name: name_ru
        required: false
        in: query
        description: name_ru
        schema:
          type: string
      - name: name_en
        required: false
        in: query
        description: name_en
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdatePost
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u0441\u0442\
          ."
        schema:
          type: string
      - name: id
        required: false
        in: query
        description: id
        schema:
          type: string
      - name: name_ru
        required: false
        in: query
        description: name_ru
        schema:
          type: string
      - name: name_en
        required: false
        in: query
        description: name_en
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyPost
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u0441\u0442\
          ."
        schema:
          type: string
      - name: id
        required: false
        in: query
        description: id
        schema:
          type: string
      - name: name_ru
        required: false
        in: query
        description: name_ru
        schema:
          type: string
      - name: name_en
        required: false
        in: query
        description: name_en
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        type_cat:
          enum:
          - ART
          - NWS
          type: string
        date_pub:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 128
        name_en:
          type: string
          nullable: true
          maxLength: 128
        name_ru:
          type: string
          nullable: true
          maxLength: 128
        content:
          type: string
        content_en:
          type: string
          nullable: true
        content_ru:
          type: string
          nullable: true
        content_rate:
          type: integer
        content_image:
          type: string
          format: binary
        post_cat:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - name
      - content
